#include <stdio.h>
#include <stdlib.h>
#include "hashtable.h"

int main(){
    ht htable;
    hashtable_create(&htable);
    char *hm = "harshmohan";
    char* name = &hm[1];
    int data = 0;
    char* name1 = "b";
    int data1 = 1;
    char* name2 = "c";
    int data2 = 2;
    char* name3 = "d";
    int data3 = 3;
    char* name4 = "e";
    int data4 = 4;
    char* name5 = "f";
    int data5 = 5;
    char* name6 = "g";
    int data6 = 6;
    char* name7 = "h";
    int data7 = 7;
    char* name8 = "i";
    int data8 = 8;
    char* name9 = "j";
    int data9 = 9;
    char* name10 = "k";
    int data10 = 10;
    char* name11 = "l";
    int data11 = 11;
    char* name12 = "m";
    int data12 = 12;
    char* name13 = "n";
    int data13 = 13;
    char* name14 = "o";
    int data14 = 14;
    char* name15 = "p";
    int data15 = 15;
    char* name16 = "q";
    int data16 = 16;
    char* name17 = "r";
    int data17 = 17;
    char* name18 = "s";
    int data18 = 18;
    char* name19 = "t";
    int data19 = 19;
    char* name20 = "u";
    int data20 = 20;
    char* name21 = "v";
    int data21 = 21;
    char* name22 = "w";
    int data22 = 10;
    char* name23 = "x";
    int data23 = 10;
    ht_set(&htable,name,&data,INT_INPUT);
    ht_set(&htable,name,&data1,INT_INPUT);
    ht_set(&htable,name,&data2,INT_INPUT);
    ht_set(&htable,name1,&data1,INT_INPUT);
    ht_set(&htable,name2,&data2,INT_INPUT);
    ht_set(&htable,name3,&data3,INT_INPUT);
    ht_set(&htable,name4,&data4,INT_INPUT);
    ht_set(&htable,name5,&data5,INT_INPUT);
    ht_set(&htable,name6,&data6,INT_INPUT);
    ht_set(&htable,name7,&data7,INT_INPUT);
    ht_set(&htable,name8,&data8,INT_INPUT);
    ht_set(&htable,name9,&data9,INT_INPUT);
    ht_set(&htable,name10,&data10,INT_INPUT);
    ht_set(&htable,name11,&data11,INT_INPUT);
    ht_set(&htable,name12,&data12,INT_INPUT);
    ht_set(&htable,name13,&data13,INT_INPUT);
    ht_set(&htable,name14,&data14,INT_INPUT);
    ht_set(&htable,name15,&data15,INT_INPUT);
    ht_set(&htable,name16,&data16,INT_INPUT);
    ht_set(&htable,name17,&data17,INT_INPUT);
    ht_set(&htable,name18,&data18,INT_INPUT);
    ht_set(&htable,name19,&data19,INT_INPUT);
    hti iterator = ht_iterator(&htable);
    ht_next(&iterator);
    printf("%s\n",iterator.key);
    printf("%d\n",*(int*)iterator.value);
    ht_next(&iterator);
    printf("%s\n",iterator.key);
    printf("%d\n",*(int*)iterator.value);
    ht_next(&iterator);
    printf("%s\n",iterator.key);
    printf("%d\n",*(int*)iterator.value);
    ht_next(&iterator);
    printf("%s\n",iterator.key);
    printf("%d\n",*(int*)iterator.value);
    ht_next(&iterator);
    printf("%s\n",iterator.key);
    printf("%d\n",*(int*)iterator.value);
    printf("%d\n",*(int*)ht_get(&htable,name));
}